INSERT INTO register_exercise (name, description)
VALUES
    ('Supino', 'Exercício para peitoral e tríceps'),
    ('Agachamento', 'Exercício para pernas, glúteos e quadríceps'),
    ('Levantamento Terra', 'Exercício para costas, pernas e glúteos'),
    ('Desenvolvimento de Ombros', 'Exercício para ombros e tríceps'),
    ('Rosca Direta', 'Exercício para bíceps'),
    ('Extensão de Tríceps', 'Exercício para tríceps'),
    ('Pulldown na Polia Alta', 'Exercício para costas e bíceps'),
    ('Leg Press', 'Exercício para pernas e quadríceps'),
    ('Curl de Pernas', 'Exercício para isquiotibiais e glúteos'),
    ('Extensão de Pernas', 'Exercício para quadríceps'),
    ('Crucifixo', 'Exercício para peitoral'),
    ('Flexões', 'Exercício para peitoral e tríceps'),
    ('Máquina de Peitoral', 'Exercício para peitoral'),
    ('Barra Fixa', 'Exercício para costas e bíceps'),
    ('Remada Curvada', 'Exercício para costas e bíceps'),
    ('Máquina de Pulldown', 'Exercício para costas e bíceps'),
    ('Elevação Lateral', 'Exercício para ombros'),
    ('Desenvolvimento Frontal', 'Exercício para ombros'),
    ('Rosca Martelo', 'Exercício para bíceps'),
    ('Leg Curl', 'Exercício para isquiotibiais'),
    ('Abdominais Tradicionais', 'Exercício para abdominais'),
    ('Prancha', 'Exercício para fortalecimento do core'),
    ('Esteira', 'Exercício cardiovascular'),
    ('Bicicleta Ergométrica', 'Exercício cardiovascular'),
    ('Elíptico', 'Exercício cardiovascular de baixo impacto'),
    ('Corrida', 'Exercício cardiovascular ao ar livre'),
    ('Natação', 'Exercício cardiovascular de corpo inteiro'),
    ('Remo', 'Exercício cardiovascular e de força'),
    ('Burpees', 'Exercício funcional de corpo inteiro'),
    ('Agachamento com Salto', 'Exercício para pernas e explosão'),
    ('Flexões de Pernas', 'Exercício para pernas e glúteos'),
    ('Mountain Climbers', 'Exercício cardiovascular e core'),
    ('Prancha Lateral', 'Exercício para os oblíquos'),
    ('Kettlebell Swings', 'Exercício para o core e explosão de quadril'),
	('Rosca Scott', 'Exercício para bíceps usando a barra Scott'),
    ('Mergulhos', 'Exercício para tríceps e peitoral'),
    ('Puxada na Máquina', 'Exercício para costas e bíceps'),
    ('Cadeira Extensora', 'Exercício para quadríceps e pernas'),
    ('Cadeira Flexora', 'Exercício para isquiotibiais e pernas'),
    ('Stiff', 'Exercício para isquiotibiais e lombar'),
    ('Flexão em Barra Fixa', 'Exercício para costas e bíceps'),
    ('Rosca Inversa', 'Exercício para bíceps e antebraços'),
    ('Abdominais Inferiores', 'Exercício para a parte inferior dos abdominais'),
    ('Rosca 21', 'Exercício para bíceps com 21 repetições'),
    ('Agachamento com Barra Z', 'Variação de agachamento com barra Z'),
    ('Climbing Stairs', 'Exercício cardiovascular subindo escadas'),
    ('Pular Corda', 'Exercício cardiovascular com corda'),
    ('Salto em Caixa', 'Exercício para saltos verticais'),
    ('Aeróbica', 'Exercício cardiovascular aeróbico'),
    ('Exercício de Escada', 'Exercício de subida e descida de escada'),
    ('Flexões em Pino', 'Variação avançada de flexões'),
    ('Agachamento Frontal', 'Variação de agachamento com a barra frontal'),
    ('Rosca Martelo Alternada', 'Exercício de bíceps alternado'),
    ('Prancha de Antebraço', 'Variação da prancha tradicional'),
    ('Agachamento com Pular', 'Agachamento com salto'),
    ('Rosca Concentrada Alternada', 'Exercício de bíceps alternado com halteres'),
    ('Prensa de Ombros', 'Exercício para ombros e tríceps na máquina'),
    ('Rosca na Corda', 'Exercício de bíceps com corda'),
    ('Flexões em Barras Paralelas', 'Flexões usando barras paralelas');