import fytnez_backend.register.models_admin.user_admin
import fytnez_backend.register.models_admin.achievement_admin
import fytnez_backend.register.models_admin.hydric_consumption_admin
import fytnez_backend.register.models_admin.user_config_admin

import fytnez_backend.register.models_admin.achievement_type_admin
import fytnez_backend.register.models_admin.user_achievement_admin
