# Generated by Django 4.2.1 on 2023-06-05 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_create_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="delete_at",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="total_points",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
