# Generated by Django 4.2.1 on 2023-06-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_update_user_validators"),
        ("register", "0002_user_create_at_user_delete_at_user_total_points_and_more"),
    ]

    operations = []
