# Generated by Django 4.2.4 on 2023-08-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_create_at_user_delete_at_user_total_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
