# Generated by Django 4.2.1 on 2023-09-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_token_user_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
