# Generated by Django 4.2.1 on 2023-08-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_achievement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="delete_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="delete_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
