# Generated by Django 4.2.1 on 2023-09-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_user_delete_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
