# Generated by Django 4.2.1 on 2023-09-13 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_achievement_delete_at_alter_user_delete_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydricConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('qnty_consumption', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
