# Generated by Django 4.2.1 on 2023-08-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_achievement_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="hex_color",
            field=models.CharField(default="#FFFFC107", max_length=9),
        ),
    ]
