# Generated by Django 4.2.1 on 2023-09-20 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_hydricconsumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('dailyHydricComsumption', models.IntegerField(help_text='ml')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
