# Generated by Django 4.2.1 on 2023-09-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0006_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="a", max_length=255),
            preserve_default=False,
        ),
    ]
