# Generated by Django 4.2.1 on 2023-09-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_userconfig'),
        ('register', '0007_refactor_achievement_structure'),
    ]

    operations = [
    ]
