# Generated by Django 4.2.1 on 2023-09-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0007_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
