# Generated by Django 4.2.1 on 2023-09-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_exercisesModels'),
        ('register', '0003_merge_20230612_2148'),
        ('register', '0006_userconfig'),
        ('register', '0007_refactor_achievement_structure'),
        ('register', '0008_alter_user_email'),
    ]

    operations = [
    ]
