# Generated by Django 4.2.1 on 2023-09-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_merge_20230919_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='hex_color',
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='', help_text='\n        Coloque a constante do icon do Angular de acordo com o seguinte site:\n        https://api.flutter.dev/flutter/material/Icons-class.html#constants\n    ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievementtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hydricconsumption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('WATER_CONSUMPTION', 'Water Consumption'), ('WORKOUT', 'Workout')], max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
